name: "DAST Scan Application"
on:
  workflow_dispatch:
    branches:
      - sectools

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
    - name: Run ZAP - Full Scan
      run:  docker run --rm -v $(pwd):/zap/wrk/:rw --user root -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://8kdkk3nk3z.us-east-1.awsapprunner.com  -x testreport.xml -r testreport.html || true
    - uses: actions/upload-artifact@v3
      with:
        name: owasp
        path: testreport.*
