name: "SAST Scan Application"
on:
  workflow_dispatch:
    branches:
      - sectools

jobs:
  check-secret:
    name: check-secret
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: horusec
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src public.ecr.aws/roxsross/horusec:v2.9.0 horusec start -p /src -P "$(pwd)" -e="true" -o="json" -O=src/horusec.json || true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python ./.github/scripts/roxs-security-tools.py horusec.json horusec
      continue-on-error: true
    - uses: actions/upload-artifact@v3
      with:
        name: horusec
        path: horusec.json

  check-trivy:
    name: check-trivy
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t trivy-image:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'trivy-image:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
